@baseUrl = http://localhost:3001/api/persons

GET {{baseUrl}}

###

POST {{baseUrl}}
Content-Type: application/json

{
    "name": "Kekalainen",
    "number": "040-404"
}

###

GET {{baseUrl}}/1

###

DELETE {{baseUrl}}/1
